### ISSUE TITLE
api mati

### ISSUE THREAD

**Issue by techwiz37** [nazri07/Create-API-With-PYTHON-FLASK-deploy-to-Heroku#1]
aktifkan lgi dong um api mnazria herokuapp

**Comment by nazri07** [comment]
:3

Pada tanggal Sel, 30 Mar 2021 07.02, Amirul Dev ***@***.***>
menulis:

**Comment by techwiz37** [comment]
mau make um :3 atau ga open source kan kodenya

**Comment by nazri07** [comment]
udeh

Pada tanggal Kam, 1 Apr 2021 00.09, Amirul Dev ***@***.***>
menulis:

**Comment by amiruldev20** [comment]
tebak gambarnua ga ada? pdhl hd di api ente
